version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  django:
    build: ./webapp
    ports:
      - 8000:8000
    volumes:
      - ./webapp:/webapp
    command: python3 manage.py runserver 0.0.0.0:8000